# On déclare le provider sous forme de liste (c'est ça qui bloquait !)
providers = ["node"]

[variables]
# On force l'utilisation de Node 20 (version LTS ultra-stable) et npm
NIXPACKS_NODE_VERSION = '20'
NIXPACKS_PACKAGE_MANAGER = 'npm'

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node .output/server/index.mjs'